import { MongoClient, Db } from "mongodb";

if (!process.env.MONGODB_URI) {
  throw new Error("Please add your MongoDB URI to .env.local");
}

const uri = process.env.MONGODB_URI;
const options = {};

let client: MongoClient;
let clientPromise: Promise<MongoClient>;

if (process.env.NODE_ENV === "development") {
  // In development mode, use a global variable so that the value
  // is preserved across module reloads caused by HMR (Hot Module Replacement).
  const globalWithMongo = global as typeof globalThis & {
    _mongoClientPromise?: Promise<MongoClient>;
  };

  if (!globalWithMongo._mongoClientPromise) {
    client = new MongoClient(uri, options);
    globalWithMongo._mongoClientPromise = client.connect();
  }
  clientPromise = globalWithMongo._mongoClientPromise;
} else {
  // In production mode, it's best to not use a global variable.
  client = new MongoClient(uri, options);
  clientPromise = client.connect();
}

// Database name
const DB_NAME = "vulntracker";

/**
 * Get the MongoDB database instance
 */
export async function getDatabase(): Promise<Db> {
  const client = await clientPromise;
  return client.db(DB_NAME);
}

/**
 * Get the CVEs collection
 */
export async function getCvesCollection() {
  const db = await getDatabase();
  return db.collection("cves");
}

/**
 * Get the Products collection
 */
export async function getProductsCollection() {
  const db = await getDatabase();
  return db.collection("products");
}

/**
 * Get the Emails collection
 */
export async function getEmailsCollection() {
  const db = await getDatabase();
  return db.collection("emails");
}

/**
 * Get the Chat Sessions collection
 */
export async function getChatSessionsCollection() {
  const db = await getDatabase();
  return db.collection("chat_sessions");
}

/**
 * Get the AI Scored CVEs collection
 * This collection contains CVSS scores generated by our AI agent system
 * for CVEs that don't have official CVSS scores
 */
export async function getAiScoredCvesCollection() {
  const db = await getDatabase();
  return db.collection("ai_scored_cves");
}

// Export the client promise for advanced use cases
export default clientPromise;
